### ISSUE TITLE
请求出一个详细的构建教程

### ISSUE THREAD

**Issue by RedShameA** [mamoe/mirai-demos#12]
为了用mirai学习了一天 Android Studio
还是没能把java demo跑起来
痛点在 添加依赖 ，老是添加不成功
-----------------------------------
或者是只能用IDEA跑这个demo吗？

**Comment by Him188** [comment]
若不熟悉 Android 平台, 请使用 JVM.

**Comment by Him188** [comment]
JVM 配置可参考 https://github.com/mamoe/mirai/blob/master/docs/guide_getting_started.md

**Comment by Him188** [comment]
或者, 可考虑编写 mirai-console 的插件. console 拥有十分详细的教程和全自动配置环境的 IntelliJ 插件. 
https://github.com/mamoe/mirai-console/blob/master/PluginDocs/ToStart.MD

**Comment by RedShameA** [comment]
哇 开发者回复的也太快了吧
谢谢！
