### ISSUE TITLE
Events.registerEvent: java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by dfaofeng** [mamoe/mirai-demos#17]
![QQ截图20200617210938](https://user-images.githubusercontent.com/14891398/84902182-09fd1d00-b0df-11ea-9651-b8a6e8e96dc4.png)
当使用at时报错,其他命令页报错,版本是最新版1.1-EA

**Comment by wasgxu** [comment]
遇到了一样的问题

**Comment by Him188** [comment]
这个是 mirai-core 的问题，请重新在 https://github.com/mamoe/mirai 创建issue. GitHub无法 transfer issue从这个项目。
