### ISSUE TITLE
请问如何撤回一条群员消息

### ISSUE THREAD

**Issue by git-zt** [mamoe/mirai-demos#22]
请问 JAVA 如何撤回一条群员消息?
使用 `bot.recall(event.getMessage)` 和 `bot.recall(event.getSource)`
都会报错
报错内容：`No message meets the requirements`

**Comment by Him188** [comment]
时间超过了2分钟？

**Comment by git-zt** [comment]
> 时间超过了2分钟？

…没…并且是撤回其他群员消息，不是撤回自己的消息
